// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_record.djinni

package com.wireless.kernel.nativeinterface;

import java.util.ArrayList;

public final class AudioBuffer {


    /*package*/ long id;

    /*package*/ ArrayList<Short> buffer = new ArrayList<Short>();

    public AudioBuffer(){}

    public AudioBuffer(
            long id,
            ArrayList<Short> buffer) {
        this.id = id;
        this.buffer = buffer;
    }

    public long getId() {
        return id;
    }

    public ArrayList<Short> getBuffer() {
        return buffer;
    }

    @Override
    public String toString() {
        return "AudioBuffer{"
                + "id=" + id + ","
                + "buffer=" + buffer + ","
                + "}";
    }

}
