// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_record.djinni

package com.wireless.kernel.nativeinterface;

public final class AudioConf {


    /*package*/ double sf;

    /*package*/ IniPosition iniP = new IniPosition();

    /*package*/ int space;

    public AudioConf(){}

    public AudioConf(
            double sf,
            IniPosition iniP,
            int space) {
        this.sf = sf;
        this.iniP = iniP;
        this.space = space;
    }

    public double getSf() {
        return sf;
    }

    public IniPosition getIniP() {
        return iniP;
    }

    public int getSpace() {
        return space;
    }

    @Override
    public String toString() {
        return "AudioConf{"
                + "sf=" + sf + ","
                + "iniP=" + iniP + ","
                + "space=" + space + ","
                + "}";
    }

}
