// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_record.djinni

package com.wireless.kernel.nativeinterface;

public final class AudioResult {


    /*package*/ long id;

    /*package*/ double x;

    /*package*/ double y;

    /*package*/ double z;

    /*package*/ double dis;

    /*package*/ double angle;

    public AudioResult(){}

    public AudioResult(
            long id,
            double x,
            double y,
            double z,
            double dis,
            double angle) {
        this.id = id;
        this.x = x;
        this.y = y;
        this.z = z;
        this.dis = dis;
        this.angle = angle;
    }

    public long getId() {
        return id;
    }

    public double getX() {
        return x;
    }

    public double getY() {
        return y;
    }

    public double getZ() {
        return z;
    }

    public double getDis() {
        return dis;
    }

    public double getAngle() {
        return angle;
    }

    @Override
    public String toString() {
        return "AudioResult{"
                + "id=" + id + ","
                + "x=" + x + ","
                + "y=" + y + ","
                + "z=" + z + ","
                + "dis=" + dis + ","
                + "angle=" + angle + ","
                + "}";
    }

}
