// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from common_record.djinni

package com.wireless.kernel.nativeinterface;

public final class DeviceInfo {


    /*package*/ String buildVer = "";

    /*package*/ int localId;

    /*package*/ String devName = "";

    /*package*/ String devType = "";

    /*package*/ String osVer = "";

    /*package*/ boolean setMute;

    public DeviceInfo(){}

    public DeviceInfo(
            String buildVer,
            int localId,
            String devName,
            String devType,
            String osVer,
            boolean setMute) {
        this.buildVer = buildVer;
        this.localId = localId;
        this.devName = devName;
        this.devType = devType;
        this.osVer = osVer;
        this.setMute = setMute;
    }

    /** 客户端编译版本号 */
    public String getBuildVer() {
        return buildVer;
    }

    /** 语言id(语言id没有系统api可以直接获取，可以先传2052（简体中文）和1033（英文）两个) */
    public int getLocalId() {
        return localId;
    }

    /** 客户端设备名 */
    public String getDevName() {
        return devName;
    }

    /** 客户端设备型号 */
    public String getDevType() {
        return devType;
    }

    /** 客户端os版本号 */
    public String getOsVer() {
        return osVer;
    }

    /** 是否静音 */
    public boolean getSetMute() {
        return setMute;
    }

    /** 客户端编译版本号 */
    public void setBuildVer(String buildVer) {
        this.buildVer = buildVer;
    }

    /** 语言id(语言id没有系统api可以直接获取，可以先传2052（简体中文）和1033（英文）两个) */
    public void setLocalId(int localId) {
        this.localId = localId;
    }

    /** 客户端设备名 */
    public void setDevName(String devName) {
        this.devName = devName;
    }

    /** 客户端设备型号 */
    public void setDevType(String devType) {
        this.devType = devType;
    }

    /** 客户端os版本号 */
    public void setOsVer(String osVer) {
        this.osVer = osVer;
    }

    /** 是否静音 */
    public void setSetMute(boolean setMute) {
        this.setMute = setMute;
    }

    @Override
    public String toString() {
        return "DeviceInfo{"
                + "buildVer=" + buildVer + ","
                + "localId=" + localId + ","
                + "devName=" + devName + ","
                + "devType=" + devType + ","
                + "osVer=" + osVer + ","
                + "setMute=" + setMute + ","
                + "}";
    }

}
