// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from common_record.djinni

package com.wireless.kernel.nativeinterface;

public final class EngineConstant {

    /**
     * ***********************@PlatformType***********************
     ** 0:Unknown
     */
    public static final int KPLATFORMTYPEUNKNOWN = 0;

    public static final int KPLATFORMTYPEANDROID = 1;

    public static final int KPLATFORMTYPEIOS = 2;

    public static final int KPLATFORMTYPEPC = 3;

    public static final int KPLATFORMTYPEMAC = 4;

    public static final int KPLATFORMTYPELINUX = 5;

    public static final int KPLATFORMTYPEIPAD = 6;

    /**
     * ***********************@AppType***********************
     ** 0:Unknown
     */
    public static final int KAPPTYPEUNKNOWN = 0;

    /** demo */
    public static final int KAPPTYPEDEMO = 1;


    public EngineConstant(
            ) {
    }

    @Override
    public String toString() {
        return "EngineConstant{"
                + "}";
    }

}
