// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from common_base.djinni

package com.wireless.kernel.nativeinterface;

import java.util.HashMap;

public interface IGlobalAdapter {
    public void onLog(int level, String msg);

    public Long onGetSrvCalTime();

    public void onShowErrUITips(String errMsg);

    public DeviceInfo getDeviceInfo();

    /** [uid] [事件码] [事件成败标识] [事件参数] [是否实时上报] */
    public void onDataReport(String uid, String eventCode, boolean isSuc, HashMap<String, String> params, boolean isRealTime);
}
