// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from common_base.djinni

package com.wireless.kernel.nativeinterface;

public interface IKernelSessionListener {
    public default void onSessionCreate(int result, String sessionId){}

    public default void onSessionInitComplete(int result, String sessionId, String uid){}
}
