// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_service.djinni

package com.wireless.kernel.nativeinterface;

import java.util.ArrayList;

public interface IKernelAudioListener {
    public default void onCalWinUpdate(ArrayList<AudioResult> datas){}

    public default void onUltraSignalUpdate(UltraResult result){}
}
