// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from common_record.djinni

package com.wireless.kernel.nativeinterface;

public final class InitSessionConfig {


    /*package*/ String selfUid = "";

    /*package*/ String sysPath = "";

    /*package*/ String userPath = "";

    /*package*/ String clientVer = "";

    /*package*/ String machineId = "";

    /*package*/ PlatformType platform = PlatformType.values()[0];

    /*package*/ String platVer = "";

    /*package*/ String defaultFileDownloadPath = "";

    public InitSessionConfig(){}

    public InitSessionConfig(
            String selfUid,
            String sysPath,
            String userPath,
            String clientVer,
            String machineId,
            PlatformType platform,
            String platVer,
            String defaultFileDownloadPath) {
        this.selfUid = selfUid;
        this.sysPath = sysPath;
        this.userPath = userPath;
        this.clientVer = clientVer;
        this.machineId = machineId;
        this.platform = platform;
        this.platVer = platVer;
        this.defaultFileDownloadPath = defaultFileDownloadPath;
    }

    public String getSelfUid() {
        return selfUid;
    }

    public String getSysPath() {
        return sysPath;
    }

    public String getUserPath() {
        return userPath;
    }

    public String getClientVer() {
        return clientVer;
    }

    public String getMachineId() {
        return machineId;
    }

    /** 终端类型 */
    public PlatformType getPlatform() {
        return platform;
    }

    /** 终端系统版本 */
    public String getPlatVer() {
        return platVer;
    }

    /** 文件的默认下载路径 */
    public String getDefaultFileDownloadPath() {
        return defaultFileDownloadPath;
    }

    @Override
    public String toString() {
        return "InitSessionConfig{"
                + "selfUid=" + selfUid + ","
                + "sysPath=" + sysPath + ","
                + "userPath=" + userPath + ","
                + "clientVer=" + clientVer + ","
                + "machineId=" + machineId + ","
                + "platform=" + platform + ","
                + "platVer=" + platVer + ","
                + "defaultFileDownloadPath=" + defaultFileDownloadPath + ","
                + "}";
    }

}
