// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from common_base.djinni

package com.wireless.kernel.nativeinterface;

public interface IOperateCallback {
    public void onResult(int rc, String msg);
}
