// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from common_record.djinni

package com.wireless.kernel.nativeinterface;

/** ip 类型 */
public enum IpType {
    /** 0 v4 */
    KV4,
    /** 1 v6 */
    KV6,
}
