// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from common_record.djinni

package com.wireless.kernel.nativeinterface;

public enum NetStatusType {
    /** 0 不可达 */
    KNOTREACHABLE,
    /** 1 wifi */
    KREACHABLEVIAWIFI,
    /** 2 2G */
    KREACHABLEVIA2G,
    /** 3 3G */
    KREACHABLEVIA3G,
    /** 4 4G */
    KREACHABLEVIA4G,
    /** 5 5G */
    KREACHABLEVIA5G,
    /** 6 unkonwn */
    KREACHABLEUNKNOWN,
}
