// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from common_record.djinni

package com.wireless.kernel.nativeinterface;

public enum PlatformType {
    KUNKNOWN,
    KANDROID,
    KIOS,
    KWINDOWS,
    KMAC,
}
