// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from common_record.djinni

package com.wireless.kernel.nativeinterface;

/** 服务地址 */
public final class ServerAddress {


    /*package*/ String ip = "";

    /*package*/ int port;

    public ServerAddress(){}

    public ServerAddress(
            String ip,
            int port) {
        this.ip = ip;
        this.port = port;
    }

    public String getIp() {
        return ip;
    }

    public int getPort() {
        return port;
    }

    @Override
    public String toString() {
        return "ServerAddress{"
                + "ip=" + ip + ","
                + "port=" + port + ","
                + "}";
    }

}
