// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_record.djinni

package com.wireless.kernel.nativeinterface;

public final class UltraResult {


    /*package*/ long id;

    /*package*/ boolean hasMaxVal;

    /*package*/ float curVal;

    /*package*/ float maxVal;

    public UltraResult(){}

    public UltraResult(
            long id,
            boolean hasMaxVal,
            float curVal,
            float maxVal) {
        this.id = id;
        this.hasMaxVal = hasMaxVal;
        this.curVal = curVal;
        this.maxVal = maxVal;
    }

    public long getId() {
        return id;
    }

    public boolean getHasMaxVal() {
        return hasMaxVal;
    }

    public float getCurVal() {
        return curVal;
    }

    public float getMaxVal() {
        return maxVal;
    }

    @Override
    public String toString() {
        return "UltraResult{"
                + "id=" + id + ","
                + "hasMaxVal=" + hasMaxVal + ","
                + "curVal=" + curVal + ","
                + "maxVal=" + maxVal + ","
                + "}";
    }

}
